#!/bin/python3
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-

import socket, curses
from curses import wrapper
from threading import *
from display import Display

def run(stdscr):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(("", 22222))
    display = Display(stdscr)
    while True:
        data, addr = s.recvfrom(1024)
        s_tmp = data.decode('utf-8').split('|')
        s_tmp1 = s_tmp[0].split('.')[0]
        s_tmp2 = s_tmp[1].split('.')[0]
        display.setSensorValues(s_tmp1, s_tmp2)
        
def main(stdscr):
    curses.curs_set(False)

    T = Thread(target=run, args=(stdscr,));
    T.setDaemon(True)
    T.start()

    c = stdscr.getch()
    while c != ord('q'):
        c = stdscr.getch()

wrapper(main)
